# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-20 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='fav_nums',
            new_name='fav_num',
        ),
    ]
