# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-21 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20170820_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='degree',
            field=models.CharField(choices=[('L', '\u521d\u7ea7'), ('M', '\u4e2d\u7ea7'), ('H', '\u9ad8\u7ea7')], max_length=2, verbose_name='\u96be\u5ea6'),
        ),
    ]
