# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-25 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20170824_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tag',
            field=models.CharField(default='', max_length=20, verbose_name='\u8bfe\u7a0b\u6807\u7b7e'),
        ),
    ]
