# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-25 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='must_know',
            field=models.CharField(default='', max_length=300, verbose_name='\u8bfe\u7a0b\u987b\u77e5'),
        ),
        migrations.AddField(
            model_name='course',
            name='what_you_learn',
            field=models.CharField(default='', max_length=300, verbose_name='\u4f60\u80fd\u5b66\u5230\u4ec0\u4e48'),
        ),
    ]
