# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-29 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170828_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='index',
            field=models.IntegerField(default=1, verbose_name='\u987a\u5e8f'),
        ),
    ]
