# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-29 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20170820_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='fav_type',
            field=models.CharField(choices=[('course', '\u8bfe\u7a0b'), ('org', '\u8bfe\u7a0b\u673a\u6784'), ('teacher', '\u8bb2\u5e08')], default='course', max_length=10, verbose_name='\u6536\u85cf\u7c7b\u578b'),
        ),
    ]
