# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-26 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_teacher_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorg',
            old_name='stu_num',
            new_name='students',
        ),
    ]
