# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-26 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_auto_20170826_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='age',
            field=models.IntegerField(default=18, verbose_name='\u5e74\u9f84'),
        ),
    ]
