# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-26 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_courseorg_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseorg',
            name='age',
        ),
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(default=18, verbose_name='\u5e74\u9f84'),
        ),
    ]
